spring.application.name=Spring 6 Hello World

server.port=8000
spring.rsocket.server.port=7000

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres
spring.r2dbc.username=postgres
spring.r2dbc.password=123456

spring.sql.init.mode=always

spring.jpa.show-sql=true